-- Batched import from 2025 ASSET REGISTER.xlsx
-- Assigned To omitted (Items Issued)
BEGIN;
DELETE FROM products WHERE "assetId" IS NOT NULL;
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL-CL-001-2022', 'Computer Laptop', 'IT Equipment', 'CG0466LG6', 'HP PAVILION *360M', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-002-2022', 'Computer Laptop', 'IT Equipment', '5CD21226WC', 'HP PRO BOOK 450', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-003-2023', 'Computer Laptop', 'IT Equipment', '5CG148125C', 'HP PAVILION', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', '2023-01-31', 1),
('CAL-CL-004-2023', 'Computer Laptop', 'IT Equipment', '8CG2415NHK', 'HP PAVILIO *360M', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-005-2023', 'Computer Laptop', 'IT Equipment', 'CND23318XC', 'HP ENVYX360', 1, 'CAL Office', 'IT dept', 'Fair', 'Operational but faulty', NULL, 1),
('CAL-CL-006-2023', 'Computer Laptop', 'IT Equipment', '5CG2093PDP', 'HP PAVILION*360', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2023-05-17', 1),
('CAL-CL-007-2023', 'Computer Laptop', 'IT Equipment', '5CD120VZMK', 'HP 340SG7', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-008-2024', 'Computer Laptop', 'IT Equipment', '5CD138D16B', 'ProBook 430 G8', 1, 'CAL Store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-009-2024', 'Computer Laptop', 'IT Equipment', 'CND2042C9F', 'HP250 Intel core i3', 1, 'CAL Office', 'IT dept', 'Fair', 'Operational but faulty', NULL, 1),
('CAL-CL-009-2024', 'Computer Laptop', 'IT Equipment', 'CND14898ND1', 'HP PROBOOK', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-010-2024', 'Computer Laptop', 'IT Equipment', '5CD1418HCR', 'HP PRO book 430', 1, 'CAL Office', 'IT dept', 'Fair', 'Operational but faulty', NULL, 1),
('CAL-CL-011-2024', 'Computer Laptop', 'IT Equipment', '5CD138D16B', 'HP ELITE PRO BOOK 430', 1, 'CAL store', 'IT dept', 'Poor', 'Need Repair', NULL, 1),
('CAL-CL-012-2024', 'Computer Laptop', 'IT Equipment', '5CG8504L09', 'HP ELITE PROBOOK 430', 1, 'CAL Office', 'IT dept', 'Fair', 'Operational but faulty', NULL, 1),
('CAL-CL-013-2024', 'Computer Laptop', 'IT Equipment', 'CND31325PP', 'HP250 Intel core i3', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-014-2024', 'Computer Laptop', 'IT Equipment', '5CG13664QQ', 'HP ELITE BOOK 830 G8', 1, 'CAL Store', 'Logistics', 'Poor', 'Need Repair', NULL, 1),
('CAL-CL-015-2024', 'Computer Laptop', 'IT Equipment', '5CG1366571', 'HP ELITE BOOK  G8', 1, 'CAL Store', 'Logistics', 'Poor', 'Need Repair', NULL, 1),
('CAL-CL-016-2024', 'Computer Laptop', 'IT Equipment', '5CG0406VFF', 'HP ELITE BOOK', 1, 'Bugesera', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-016-2025', 'Computer Laptop', 'IT Equipment', '5CD5022KKP', 'HP PoBook G8', 1, 'Kagarama', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-017-2025', 'Computer Laptop', 'IT Equipment', '5CD34828WX', 'ProBook 430 G10', 1, 'Bugesera', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-018-2025', 'Computer Laptop', 'IT Equipment', '8CG5111YKT', 'HP  Envy', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-019-2025', 'Computer Laptop', 'IT Equipment', '8CG4363V6G', 'HP', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-020-2025', 'Computer Laptop', 'IT Equipment', '8CG5030RW1', 'HP (envyx360)', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-09-17', 1),
('CAL-CL-021-2025', 'Computer Laptop', 'IT Equipment', '5CD4527NTF', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-01-09', 1),
('CAL-CL-021-2025', 'Computer Laptop', 'IT Equipment', '5CG8333T9P', 'ELITEBOOK', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-022-2025', 'Computer Laptop', 'IT Equipment', '5CD50421K4', 'HP BOOK440G10', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-023-2025', 'Computer Laptop', 'IT Equipment', '5CD5016VG9', 'HP Probook', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-024-2025', 'Computer Laptop', 'IT Equipment', 'CND438436Z', 'ELITEBOOK', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CL-025-2025', 'Computer Laptop', 'IT Equipment', '5CG8333TDX', NULL, 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-06-08', 1),
('CAL-CAIO-001-2022', 'Computer All in one', 'IT Equipment', '8CC103360H', 'HP 24-dI0256nh', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CAIO-002-2023', 'Computer All in one', 'IT Equipment', '8CC3090YD9', 'HP INTEL CORE i5', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CAIO-003-2023', 'Computer All in one', 'IT Equipment', '8CC2382ZSS', 'HP INTEL CORE i5', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2023-09-15', 1),
('CAL-CAIO-004-2025', 'Computer All in one', 'IT Equipment', '8CC3090YD6', 'HP 23.8inch', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CAIO-005-2025', 'Computer All in one', 'IT Equipment', '8CC404125P', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-007-2022', 'Computer Monitor', 'IT Equipment', '3CQ1271D1Y', 'HP 23.8inch', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-003-2022', 'Computer Monitor', 'IT Equipment', '3CG12171D2W', 'HP 23.8 inch', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-003-2023', 'Computer Monitor', 'IT Equipment', '3CM12903NG', 'HP 23.8 inch', 1, 'CAL ctrl.Rm', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-004-2023', 'Computer Monitor', 'IT Equipment', '3CQ12811LJ', 'HP PAVILIO *360M', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', '2023-01-01', 1),
('CAL-CM-005-2023', 'Computer Monitor', 'IT Equipment', '3CQ12290BCO', 'HP 23.8 inch', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-006-2023', 'Computer Monitor', 'IT Equipment', '3CQ12811LY', 'HP V241 ib23.8 inch', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2023-05-17', 1),
('CAL-CM-007-2023', 'Computer Monitor', 'IT Equipment', '3CM14817XT', NULL, 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-008-2024', 'Computer Monitor', 'IT Equipment', '3CM4012YSM', 'HP M27ffnd', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-009-2024', 'Computer Monitor', 'IT Equipment', '3CM4030VW1', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-010-2025', 'Computer Monitor', 'IT Equipment', '3CM4031LLP', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-01-09', 1),
('CAL-CM-011-2025', 'Computer Monitor', 'IT Equipment', '3CM313ID76', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CM-012-2025', 'Computer Monitor', 'IT Equipment', '3CM4241J7N', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-KB-001-2022', 'key board &Mouse', 'IT Equipment', '20WW1DUD60', 'HP 24-dI0256nh', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-KB-002-2022', 'key board &Mouse', 'IT Equipment', '9GCMCB211963553', 'HP', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-KB-003-2022', 'key board &Mouse', 'IT Equipment', '9GCMCB220167710', 'HP', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-KB-004-2033', 'key board &Mouse', 'IT Equipment', '9GCMB210589504', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-07-14', 1),
('CAL-KB-005-2023', 'key board &Mouse', 'IT Equipment', '9GCMCB230123947', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL-KB-006-2023', 'key board &Mouse', 'IT Equipment', 'N/A', 'HP', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', '2023-01-01', 1),
('CAL-KB-007-2023', 'key board &Mouse', 'IT Equipment', '9GCMCB220163345', 'HP wireless', 1, 'In store', 'IT dept', 'Good', 'No issues', '2023-05-17', 1),
('CAL-KB-008-2023', 'key board &Mouse', 'IT Equipment', 'M5296-L31', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-KB-009-2024', 'key board &Mouse', 'IT Equipment', '/9GCMCB230053105', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-KB-010-2024', 'key board &Mouse', 'IT Equipment', 'PIN:M52961-L31', 'HP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-PR-001-2022', 'Printer', 'IT Equipment', 'XNCRK02960', 'LESER JET PRO MFP 130', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-PR-002-2022', 'Printer', 'IT Equipment', 'XASSL30559', 'HP EPSON L3250', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-PR-003-2023', 'Printer', 'IT Equipment', 'RA35L30538', 'HP EPISON L3250', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-PR-004-2023', 'Printer', 'IT Equipment', 'XXATWQ84539', 'HP EPSON L31350', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-PR-005-2024', 'Printer', 'IT Equipment', '2NM1JC9001149', 'HP MFP179fnw', 1, 'CAL Store', 'Log.Dept', 'Damaged', 'Need Repair', NULL, 1),
('CAL-PR-006-2024', 'Printer', 'IT Equipment', 'X6HJ081624', 'HP EPSON L3156', 1, 'CAL Store', 'Log.dept', 'Damaged', 'Need Repair', NULL, 1),
('CAL-PR-007-2024', 'Printer', 'IT Equipment', 'VNC3338108', 'HP MFP183fwI', 1, 'CAL Store', 'Log.dept', 'Damaged', 'Need Repair', NULL, 1),
('CAL-PR-008-2024', 'Printer', 'IT Equipment', 'CNB1R212TV', 'HP MFP137fnw', 1, 'Kagarama', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-PR-009-2024', 'Printer', 'IT Equipment', 'CNB1R21ZZ3', 'HP137FW', 1, 'Bugesera', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-PR-010-2025', 'Printer', 'IT Equipment', 'TTUK28805', 'KM-C454e', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-RT-001-2024', 'Router', 'IT Equipment', 'ALCLB2CD966F', 'CANAL/G-0425G-A', 1, 'CAL Store', 'Log Dpt.', 'Good', 'No issues', NULL, 1),
('CAL-RT-002-2024', 'Router', 'IT Equipment', 'ALCLFCDEB226', 'NOKIA/G-140W-G', 1, 'CAL Store', 'Log Dpt.', 'Good', 'No issues', NULL, 1),
('CAL-RT-003-2024', 'Router', 'IT Equipment', '222C418000114', 'ARCHER C86', 1, 'CAL Store', 'Log Dpt.', 'Good', 'No issues', NULL, 1),
('CAL-RT-004-2024', 'Router', 'IT Equipment', 'U40D124024168', 'D-LINK /DWR-MR-M960 A2', 1, 'CAL Store', 'Log Dpt.', 'Good', 'No issues', NULL, 1),
('CAL-RT-005-2024', 'Router', 'IT Equipment', 'M162420ALU00081023', 'NOKIA/G-140W-G', 1, 'Bugesera', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-RT-006-2024', 'Router', 'IT Equipment', 'M16240ALU00080255', 'NOKIA/G-140W-G', 1, 'CAL Store', 'Log. Dpt.', 'Good', 'No issues', NULL, 1),
('CAL-RT-007-2024', 'Router', 'IT Equipment', 'ALCLB2CD96D3', 'CANAL/G-0425G-A', 1, 'CAL Store', 'Log. Dpt.', 'Good', 'No issues', NULL, 1),
('CAL-RT-008-2025', 'Router', 'IT Equipment', 'ALCLB4335EB2', 'NOKIA G-0425G-A', 1, 'CAL Office-Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-RT-009-2025', 'Router', 'IT Equipment', '2222C418000527', 'TP LINK', 1, 'CAL Office-Insttaled', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-RT-010-2025', 'Router', 'IT Equipment', 'U40D124024146', 'D-LINK /DWR-MR-M961', 1, 'Kagarama- Installed', 'IT dept', 'Good', 'No issues', '2025-10-21', 1),
('CAL-RT-011-2025', 'Router', 'IT Equipment', 'U403123000614', 'D-LINK /DWR-MR-M921', 1, 'CAL Office-Installed', 'IT dept', 'Good', 'No issues', '2025-10-21', 1),
('CAL-HDD-001-2025', 'NVR', 'IT Equipment', 'FK6694334', 'DS-7608NI-Q1/8P', 1, 'CAL Ctrl-RM', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-HDD-001-2026', 'NVR', 'IT Equipment', 'AB2711212', 'DS-7608NI-Q1/8P', 1, 'Kagarama', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-HDD-001-2027', 'NSCP & it''s Accessories', 'IT Equipment', 'Q18002520', 'DS19A08-01BNG', 1, 'Arms store', 'Log.Dept.', 'Good', 'No issues', NULL, 1),
('CAL-HDD-001-2028', 'Door Lock sysyem', 'IT Equipment', 'N/A', NULL, 1, 'Co-CEO''s Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-HDD-001-2025', 'Hard drive', 'IT Equipment', 'WX32D354YSF3', 'WD40EFPX-68C6CN0-4TB', 1, 'CAL Office-Installed', 'IT dept', 'Good', 'No issues', '2025-09-30', 1),
('CAL-HDD-002-2025', 'Hard drive', 'IT Equipment', 'WX42D854MKY', 'WD40EFPX-68C6CN0-4TB', 1, 'CAL Office-Installed', 'IT dept', 'Good', 'No issues', '2025-03-11', 1),
('CAL-QNAP-001-2025', 'QNAP', 'IT Equipment', 'QGAG407209G', 'TS-464-8GB RAM', 1, 'CAL Office-Installed', 'IT dept', 'Good', 'No issues', '2025-09-30', 1),
('CAL-RACK-001-2025', 'Rack', 'IT Equipment', 'N/A', 'METAL', 1, 'Kagarama- Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-RACK-002-2025', 'Rack', 'IT Equipment', 'N/A', 'METAL', 1, 'Kagarama- Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-SW-001- 2025', 'Swicth', 'IT Equipment', 'N/A', 'N/A', 1, 'Kagarama- Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-UPS-001-2023', 'UPS', 'IT Equipment', '86-EE2D-E37C-DBB3', 'SMT1500IT', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-UPS-002-2024', 'UPS', 'IT Equipment', '99-6BF3-E3C7-F90F', 'SMT1500IT', 1, 'CAL Off.  Ctrl Rm', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-CPU-001-2024', 'CPU', 'IT Equipment', '4CE311CS33', 'HP', 1, 'CAL Off.  Ctrl Rm', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-UPS-003-2023', 'UPS', 'IT Equipment', '210312E2000S99', 'ELITE 20000 SMART', 1, 'HR', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TV-001-2023', 'SMART TV 55''''UHD', 'Elect. Divice', NULL, 'SHARP', 1, 'Kagarama', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TV-002-2024', 'SMART TV 50''''UHD', 'Elect. Divice', NULL, 'SAMSUNG', 1, 'Co-CEO''s Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TV-003-2024', 'SMART TV 55''''UHD', 'Elect. Divice', '08J03K4X300033', 'SAMSUNG', 1, 'CAL  -Board Room', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TV-004-2024', 'SMART TV 55''''UHD WEBOS', 'Elect. Divice', '55T1TSAY240071', 'KING 55 T1-T5', 1, 'Bugesera', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TV-005-2024', 'SMART TV 32''''UHD', 'Elect. Divice', '3TE32F22220701BFAA10707', 'HISENSE/32A4M', 1, 'Bugesera', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TV-006-2024', 'SMART TV 55''''UHD', 'Elect. Divice', NULL, 'SHARP', 1, 'CAL Off. – Ctrl Rm', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-001-2023', 'Smart phone', 'Comm.Device', NULL, 'SAMSANG', 1, 'CSG Office', 'IT dept', NULL, 'Stolen', NULL, 1),
('CAL-TEL-002-2023', 'Smart phone', 'Comm.Device', 'BF6-SE668SABCDE', 'Techno POP', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-003-2023', 'SAMSANG TAB A8', 'Comm.Device', 'R8W407W0XB', 'SM-X205', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-004-2024', 'Smart phone', 'Comm.Device', 'FFWXMGGKKPH2', 'iPhone X Max', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL-TEL-005-2024', 'Smart phone', 'Comm.Device', 'RFCR80FFHZP', 'Galexy z Fold 5G', 1, 'CAL store', 'Log.Dept.', 'Poor', 'reiper', NULL, 1),
('CAL-TEL-006-2024', 'Smart phone', 'Comm.Device', 'R3CR40MY4EP', 'SM-N986UI(Galexy Note20)', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-007-2024', 'Smart phone', 'Comm.Device', 'RZCTB1D7N5L', 'SM-A336E/DSN', 1, 'CSG Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-008-2024', 'Smart phone', 'Comm.Device', 'RZCX62A392Z', 'SUMSANG-X205', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-009-2024', 'Smart phone', 'Comm.Device', 'IME11:860880075234348', 'AIRTEL H5032U', 1, 'Kagasa Post', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-010-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070443766', 'MT IKOSORA+', 1, 'KBC', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-011-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070443220', 'MT IKOSORA+', 1, 'KBC', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-012-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070071260', 'MT IKOSORA+', 1, 'Motor(MD Resid)', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-013-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070445944', 'MT IKOSORA+', 1, 'Scotia', 'IT dept', 'Untrackable', 'Not found', NULL, 1),
('CAL-TEL-014-2024', 'Smart phone', 'Comm.Device', 'IME11: 862645070442800', 'MT IKOSORA+', 1, 'Remco', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-015-2024', 'Smart phone', 'Comm.Device', 'IME11: 862645070446561', 'MT IKOSORA+', 1, 'Biontech', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-016-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508872120', 'Techno 101', 1, 'Gacuriro W/H', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-017-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508872328', 'Techno 101', 1, 'Musanze', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-018-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508913726', 'Techno 101', 1, 'Gikondo II', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-019-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508914229', 'Techno 101', 1, 'Kagugu Appt T14', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-020-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508585623', 'Techno 101', 1, 'Gisozi Residance', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-021-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508912686', 'Techno 101', 1, 'Gigkondo I', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-022-2044', 'Smart phone', 'Comm.Device', 'IME11:351995508912868', 'Techno 101', 1, 'Gishushu Appt', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-023-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508864424', 'Techno 101', 1, 'IDS (Shelter group)', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-024-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508872344', 'Techno 101', 1, 'Gacuriro W/H', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-025-2024', 'Smart phone', 'Comm.Device', 'IME11:351995508913742', 'Techno 101', 1, 'Green house', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-026-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070445142', 'MT Ikosora+', 1, 'CAL store', 'Log.Dept.', 'Poor', 'disposal', NULL, 1),
('CAL-TEL-027-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070444285', 'MT Ikosora+', 1, 'CAL store', 'Log.Dept.', 'Poor', 'disposal', NULL, 1),
('CAL-TEL-028-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070477384', 'MT Ikosora+', 1, 'CAL store', 'Log.Dept.', 'Poor', 'disposal', NULL, 1),
('CAL-TEL-029-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070443147', 'MT Ikosora+', 1, 'CAL store', 'Log.Dept.', 'Poor', 'disposal', NULL, 1),
('CAL-TEL-030-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070443527', 'MT Ikosora+', 1, 'CAL store', 'Log.Dept.', 'Poor', 'disposal', NULL, 1),
('CAL-TEL-031-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070446025', 'MT Ikosora+', 1, 'CAL store', 'Log.Dept.', 'Poor', 'disposal', NULL, 1),
('CAL-TEL-034-2024', 'Smart phone', 'Comm.Device', 'IME11:862645070440747', 'MT Ikosora+', 1, 'CAL store', 'Log.Dept.', 'Poor', 'disposal', NULL, 1),
('CAL-TEL-037-2024', 'Smart phone', 'Comm.Device', 'IME11:860880075234348', 'aitel', 1, 'Store', 'Log. Dept.', 'Good', 'No issues', NULL, 1),
('CAL-TEL-038-2024', 'Brick phone', 'Comm.Device', 'IME11: 351995508782436', 'Techno 101', 1, 'Vision City', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL-TEL-039-2024', 'Brick phone', 'Comm.Device', 'IME11: 351995508808538', 'Techno 101', 1, 'Nduba', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL- TEL-040-2025', 'Smart phone', 'Comm.Device', 'R5CY61KV24N', 'SAMSUNG A26', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL- TEL-041-2025', 'Smart phone', 'Comm.Device', 'IMEI:866981071831618', 'HONOR X8c', 1, 'CAL Office', 'IT dept', NULL, 'stolen', '2025-03-05', 1),
('CAL- TEL-042-2025', 'Smart phone', 'Comm.Device', NULL, 'HONOR X8c', 1, 'CAL Office', 'IT dept', 'Good', 'Taken to RURA', '2025-03-05', 1),
('CAL- TEL-043-2025', 'Smart phone', 'Comm.Device', 'ABQBUT4C25003672', 'HONOR X8c', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-03-05', 1),
('CAL- TEL-044-2025', 'Smart phone', 'Comm.Device', 'ABQBUT4C24001618', 'HONOR X8c', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-03-05', 1),
('CAL- TEL-045-2025', 'Smart phone', 'Comm.Device', 'ABQBUT4C24002236', 'HONOR X8c', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-03-05', 1),
('CAL- TEL-046-2025', 'Smart phone', 'Comm.Device', 'ABQBUT4C25007245', 'HONOR X8c', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-03-05', 1),
('CAL- TEL-047-2025', 'Smart phone', 'Comm.Device', 'ABQBUTAC24002236', 'HONOR X8c', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-03-05', 1),
('CAL- TEL-048-2025', 'Smart phone', 'Comm.Device', 'ABQBUT4C60023063', 'HONOR X8c', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-03-05', 1),
('CAL- TEL-049-2025', 'Smart phone', 'Comm.Device', 'R5CY83CLOOP', 'Galaxy A26 5G', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-03-05', 1),
('CAL- TEL-050-2025', 'Smart phone', 'Comm.Device', 'IMEI:352264493962357', 'TECNO POP 10', 1, 'CAL Office', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL-TEL- 051-2025', 'Smart phone', 'Comm.Device', 'IMEI:352264494062538', 'TECNO POP 10', 1, 'Kagarama', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL-TEL-052-2025', 'Smart phone', 'Comm.Device', 'IMEI1:864434070100702', 'MTN IKOSORA+', 1, 'Nyabagendwa Gate', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL-TEL-053-2025', 'Smart phone', 'Comm.Device', 'IMEI1:864434070100884', 'MTN IKOSORA+', 1, 'NKIA Supervisor', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL-TEL-054-2025', 'Smart phone', 'Comm.Device', 'IMEI1:864434070099243', 'MTN IKOSORA+', 1, 'Nyamata Gate', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL-TEL-055-2025', 'Smart phone', 'Comm.Device', 'IMEI1:864434070101049', 'MTN IKOSORA+', 1, 'Asphalt Plant', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL-TEL-056-2025', 'Smart phone', 'Comm.Device', 'IMEI1:864434070100843', 'MTN IKOSORA+', 1, 'Ririma Gate', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL-TEL-057-2025', 'Smart phone', 'Comm.Device', 'IMEI1:864434070101080', 'MTN IKOSORA+', 1, 'Camp site', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL-TEL-058-2025', 'Smart phone', 'Comm.Device', 'IMEI1:864434070101189', 'MTN IKOSORA+', 1, 'Substation South', 'IT dept', 'Good', 'No issues', '2025-11-19', 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL-TEL-059-2025', 'Smart phone', 'Comm.Device', 'IMEI1:864434070098252', 'MTN IKOSORA+', 1, 'Substation South', 'IT dept', 'Good', 'No issues', '2025-11-19', 1),
('CAL -001-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4618', 'UV-9R PLUS', 1, 'KBC', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL -002-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4974', 'UV-9R PLUS', 1, 'KBC', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL -003-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4991', 'UV-9R PLUS', 1, 'KBC', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL -003-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4996', 'UV-9R PLUS', 1, 'KBC', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL -004-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4997', 'UV-9R PLUS', 1, 'KBC', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL -006-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4804', 'UV-9R PLUS', 1, 'store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -007-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4573', 'UV-9R PLUS', 1, 'Store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -008-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4805', 'UV-9R PLUS', 1, 'Store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -009-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4989', 'UV-9R PLUS', 1, 'Store', 'Log. Dept', 'Untrackable', 'Not found', NULL, 1),
('CAL -010-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4557', 'UV-9R PLUS', 1, 'Store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -011-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS2229', 'UV-9R PLUS', 1, 'Store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -012-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', NULL, 'UV-9R PLUS', 1, 'Taken to  Guinea', NULL, 'taken as sample', 'Follow-up Needed', NULL, 1),
('CAL -013-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', NULL, 'UV-9R PLUS', 1, 'Taken to  Guinea', NULL, 'taken as sample', 'Follow-up Needed', NULL, 1),
('CAL -014-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', NULL, 'UV-9R PLUS', 1, 'Taken to  Guinea', NULL, 'taken as sample', 'Follow-up Needed', NULL, 1),
('CAL -015-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', NULL, 'UV-9R PLUS', 1, 'Taken to  Guinea', NULL, 'taken as sample', 'Follow-up Needed', NULL, 1),
('CAL -016-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4993', 'UV-9R PLUS', 1, 'IDS(PARKLINE)', 'Opns Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -017-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4560', 'UV-9R PLUS', 1, 'IDS(PARKLINE)', 'Opns Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -018-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4649', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -019-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4647', 'UV-9R PLUS', 1, 'Remco', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL -020-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4803', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -021-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4883', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -022-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS 4648', 'UV-9R PLUS', 1, 'Remco', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -023-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4869', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -024-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4619', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -025-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4870', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -026-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4646', 'UV-9R PLUS', 1, 'Remco', 'Opns  Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -027-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4615', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -028-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4882', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -029-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4975', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -030-CD-2024', 'Baofeng  walkie-talkie', 'Comm.Device', '22E70PLUS4574', 'UV-9R PLUS', 1, 'In store', 'Log. Dept', 'Not in use', 'Needs battery', NULL, 1),
('CAL -001-CD-2024', 'Motorora walkie-talkie', 'Comm.Device', '69010XEY554', 'T42', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -002-CD-2024', 'Motorora walkie-talkie', 'Comm.Device', '69010XEN061', 'T42', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -003-CD-2024', 'Motorora walkie-talkie', 'Comm.Device', '69010XAD082', 'T42', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -004-CD-2024', 'Motorora walkie-talkie', 'Comm.Device', '69010XA5977', 'T42', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -005-CD-2024', 'Motorora walkie-talkie', 'Comm.Device', '69010XAV401', 'T42', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -005-CD-2024', 'Motorora walkie-talkie', 'Comm.Device', '69010XE5607', 'T42', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -CD-001-2024', 'Alecto walkie -talkie', 'Comm.Device', 'N/A', 'FR-175', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -CD-002-2024', 'Alecto walkie -talkie', 'Comm.Device', 'N/A', 'FR-175', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -CD-003-2024', 'Alecto walkie -talkie', 'Comm.Device', 'N/A', 'FR-175', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -CD-004-2024', 'Alecto walkie -talkie', 'Comm.Device', 'N/A', 'FR-175', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -CD-005-2024', 'Alecto walkie -talkie', 'Comm.Device', 'N/A', 'FR-176', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -CD-006-2024', 'Alecto walkie -talkie', 'Comm.Device', 'N/A', 'FR-177', 1, 'Store', 'Log. Dept', 'Good', 'No issues', NULL, 1),
('CAL -CD-001-2024', 'Rover', 'Comm.Device', '2304E00854', 'R-10', 1, 'Store', 'Log. Dept', 'damaged', 'disposal', NULL, 1),
('CAL -CD-002-2024', 'Rover', 'Comm.Device', '2304E00853', 'R-10', 1, 'Store', 'Log. Dept', 'Poor', 'disposal', NULL, 1),
('CAL - CD-003-2024', 'Rover', 'Comm.Device', '2304E00753', 'R-10', 1, 'Store', 'Log. Dept', NULL, 'disposal', NULL, 1),
('CAL -CD-004-2024', 'Rover', 'Comm.Device', '2304E00754', 'R-10', 1, 'Store', 'Log. Dept', 'Poor', 'disposal', NULL, 1),
('CAL -CD-005-2024', 'Rover', 'Comm.Device', '2304E00852', 'R-10', 1, 'Store', 'Log. Dept', 'Poor', 'disposal', NULL, 1),
('CAL -CD-006-2024', 'Rover', 'Comm.Device', '2205E01450', 'R-10', 1, 'Store', 'Log. Dept', 'Poor', 'disposal', NULL, 1),
('CAL -CD-005-2024', 'Rover', 'Comm.Device', '2205E01559', 'R-10', 1, 'Store', 'Log. Dept', NULL, 'disposal', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL -CD-006-2024', 'Rover', 'Comm.Device', '2304E00851', 'R-10', 1, 'Store', 'Log. Dept', NULL, 'disposal', NULL, 1),
('CAL -CD-007-2024', 'Rover', 'Comm.Device', '2304E01449', 'R-10', 1, 'Store', 'Log. Dept', 'Poor', 'disposal', NULL, 1),
('CAL -CD-008-2024', 'Rover', 'Comm.Device', '2304E01560', 'R-10', 1, 'Store', 'Log. Dept', 'Poor', 'disposal', NULL, 1),
('CAL -CD-001-2024', 'STN', 'Comm.Device', '1807AO3598', NULL, 1, 'Store', 'Log. Dpt', 'damaged', 'disposal', NULL, 1),
('CAL -CD-002-2024', 'STN', 'Comm.Device', '1807A03508', NULL, 1, 'Store', 'Log. Dpt', 'damaged', 'disposal', NULL, 1),
('CAL -CD-001-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB085', 'MDH11JDC9JA2AN', 1, 'Kinigi Singta', 'Opns dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-002-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB118', 'MDH11JDC9JA2AN', 1, 'Kinigi Singta', 'Opns dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-003-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB514', 'MDH11JDC9JA2AN', 1, 'Kinigi Singta', 'Opns dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-004-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB530', 'MDH11JDC9JA2AN', 1, 'Store', 'Opns dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-005-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB819', 'MDH11JDC9JA2AN', 1, 'Kinigi Singta', 'Opns dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-006-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB767', 'MDH11JDC9JA2AN', 1, 'Store', 'Log. Dpt', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-007-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EAR6074', 'MDH11JDC9JA2AN', 1, 'Kinigi Singta', 'IT dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-008-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB238', 'MDH11JDC9JA2AN', 1, 'Kinigi Singta', 'IT dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-009-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB179', 'MDH11JDC9JA2AN', 1, 'Kinigi Singta', 'IT dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL -CD-010-2025', 'Moto- R2VHF PN1302C', 'Comm.Device', '902EBQB819', 'MDH11JDC9JA2AN', 1, 'Kinigi Singta', 'IT dept', 'Good', 'No Issues', '2025-11-21', 1),
('CAL.CD-001-2024', 'Round speeker big', 'Comm.Device', '2408LZS1BQF8', 'LOGI/V-U0036', 1, 'Board Room', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.CD-002-2024', 'Round speeker small', 'Comm.Device', '2409LZ50V988', 'LOGI', 1, 'Board Room', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.CD-003-2024', 'Round speeker small', 'Comm.Device', '2409LZ50V908', 'LOGI', 1, 'Board Room', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -001-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'KBC', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -004-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'BIONITEC', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -005-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH101', 1, 'BIONITEC', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -006-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Vision City', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -007-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Vision City', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -010-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -011-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -012-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -013-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -014-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -014-2025', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -014-2026', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH102', 1, 'Store', 'Log.Dept', 'Poor', 'disposal', NULL, 1),
('CAL.HMD -014-2027', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH103', 1, 'Store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -015-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -016-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -017-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -018-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'Store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -019-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'NKIA', 'Opn Dept', 'Poor', 'disposal', NULL, 1),
('CAL.HMD -020-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH100', 1, 'NKIA', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -021-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH102', 1, 'NKIA', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -022-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH103', 1, 'NKIA', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -023-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH104', 1, 'NKIA', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -024-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH105', 1, 'NKIA', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.HMD -025-2024', 'H/H Metal Det.', 'Security Eqpt.', 'N/A', 'NP-SH106', 1, 'NKIA', 'Opn Dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-001-2024', 'Walk through detector', 'Security Eqpt.', 'N/A', 'N/A', 1, 'CAL Office', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-002-2024', 'UV Search Mirror', 'Security Eqpt.', 'N/A', 'N/A', 1, 'KBC', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-003-2024', 'UV Search Mirror', 'Security Eqpt.', 'N/A', 'N/A', 1, 'KBC', 'Opns Dept', 'Poor', 'disposal', NULL, 1),
('CAL.WTMD-004-2024', 'UV Search Mirror', 'Security Eqpt.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-005-2024', 'UV Search Mirror', 'Security Eqpt.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-006-2024', 'UV Search Mirror', 'Security Eqpt.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-001-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-002-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL.WTMD-004-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-005-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-006-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-007-2024', 'Hik Vision Dome4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-008-2024', 'Hik Vision Dome4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-009-2024', 'Hik Vision Dome4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-010-2024', 'Hik Vision Dome4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL Off. installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-011-2024', 'Hik Vision Dome4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'CAL store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-012-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'Kagarama. Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-013-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'Kagarama. Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-014-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'Kagarama. Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-015-2024', 'PTZ Camera', 'Security Eqpt.', 'N/A', 'Hikvision', 1, 'Kagarama. Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-016-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'FG2372629', 'DS-2CD1047G2H-LIU', 1, 'Kagarama. Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-017-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'FG2372630', 'DS-2CD1047G2H-LIU', 1, 'Kagarama. Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-018-2024', 'Hik Vision Bulet4pm', 'Security Eqpt.', 'FG2372744', 'DS-2CD1047G2H-LIU', 1, 'Kagarama. Installed', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.WTMD-019-2024', 'Video camera', 'Security Eqpt.', 'N/A', 'LOGI', 1, 'Board Room.intalled', 'IT dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-001-2024', 'Chair bench', 'Furn. & Fitt.', 'N/A', 'W&M Foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-002-2024', 'Chair bench', 'Furn. & Fitt.', 'N/A', 'W&M Foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-003-2024', 'Chair bench', 'Furn. & Fitt.', 'N/A', 'W&M Foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-004-2024', 'Chair bench', 'Furn. & Fitt.', 'N/A', 'W&M Foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-005-2024', 'Chair bench', 'Furn. & Fitt.', 'N/A', 'W&M Foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-006-2024', 'Chair bench', 'Furn. & Fitt.', 'N/A', 'W&M Foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-008-2024', 'Office Chair mesh', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Co-CEO''S Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-009-2023', 'Office Chair mesh', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & Porj.Mgr Offi.', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-009-2023', 'Office Chair mesh', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & Porj.Mgr Offi.', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-009-2023', 'Office Chair mesh', 'Furn. & Fitt.', 'N/A', 'Polyester (Non/Adj.)', 1, 'Opns & Porj.Mgr Offi.', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-007-2024', 'Exective Office Chair', 'Furn. & Fitt.', 'N/A', 'Leather', 1, 'Co-CEO''S Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-013-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-014-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-015-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-016-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-017-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-018-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-019-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-020-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-021-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-022-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-023-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-024-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-025-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-026-2024', 'Off. chair MS 2101H', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-028-2024', 'Office Chair msh', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'HR', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-029-2024', 'Office Chair mesh', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'HR', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-030-2023', 'Office chair MS202', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Finance Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-031-2023', 'Office chair MS203', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Finance Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-032-2023', 'Office chair MS204', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Finance Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-012-2024', 'Office Chair mesh', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-033-2023', 'Office chair MS205', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-034-2024', 'Office chair MS206', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-035-2024', 'Office chair MS207', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL.FUR-CH-036-2024', 'Office chair MS208', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-037-2024', 'Office chair MS209', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-038-2024', 'Office chair MS210', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-040-2024', 'Office chair MS212', 'Furn. & Fitt.', 'N/A', 'Polyester (Non /Adj)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-041-2024', 'Office chair MS213', 'Furn. & Fitt.', 'N/A', 'Polyester (Non /Adj)', 1, 'Opns & IT Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-042-2024', 'Office chair MS214', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Log & Procur.Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-043-2024', 'Office chair MS215', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Log & Procur.Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-044-2024', 'Office Chair', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Log & Procur.Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-044-2024', 'Office Chair', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Reception', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-044-2024', 'Office Chair', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'D/Legal affairs Off.', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-044-2024', 'Office Chair', 'Furn. & Fitt.', 'N/A', 'Polyester (H/Adj.)', 1, 'Control Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-044-2024', 'Office Chair', 'Furn. & Fitt.', 'N/A', 'Polyester (Non /Adj)', 1, 'Control Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-046-2024', 'Small cabinet with sofa', 'Furn. & Fitt.', 'N/A', 'Sofa', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-047-2024', 'Small cabinet with sofa', 'Furn. & Fitt.', 'N/A', 'Sofa', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-048-2024', 'Small cabinet with sofa', 'Furn. & Fitt.', 'N/A', 'Sofa', 1, 'Board Room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-049-2024', 'Sofa set', 'Furn. & Fitt.', 'N/A', 'Sofa', 1, 'Office of Co-CEO', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-050-2024', 'Sofa set', 'Furn. & Fitt.', 'N/A', 'Sofa', 1, 'Reception', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-051-2023', 'Sofa set', 'Furn. & Fitt.', 'N/A', 'Sofa', 1, 'CSG', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-052-2022', 'Sofa set', 'Furn. & Fitt.', 'N/A', 'Sofa', 1, 'CSG', 'HR dept', 'Old', 'No issues', NULL, 1),
('CAL.FUR-CH-045-2024', 'Wooden chair', 'Furn. & Fitt.', 'N/A', 'Wood made', 1, 'Kagarama', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-053-2024', 'Plastic Chair', 'Furn. & Fitt.', 'N/A', 'N/A', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-054-2024', 'Plastic Chair', 'Furn. & Fitt.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('WTR-BTL-001-2024', 'Water bottle', 'Office Equip.', 'N/A', 'Inyange Bottle', 6, 'CAL Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('WTR-DSP-001-2023', 'Water Dispensor', 'Office Equip.', 'AQ/20200702363', 'MWD302SBL', 1, 'Reception', 'HR dept', 'Good', 'No issues', NULL, 1),
('WTR-TNK-002-2025', 'Water Dispensor', 'Office Equip.', 'AQ20240810889', 'MWD2303B', 1, 'Operation staff', 'HR dept', 'Good', 'No issues', NULL, 1),
('WTR-TNK-001-2024', 'Water tank (10m3) Each', 'Office Equip.', 'N/A', 'Plastic (ROTO)', 2, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('WTR-FLT-002-2025', 'Water tank (5m3) Each', 'Office Equip.', 'N/A', 'Plastic (AFRI -TANK)', 2, 'Bugesera', 'Opns Dept', 'Good', 'No issues', '2025-03-10', 1),
('WTR-FLT-001-2023', 'Water Filter', 'Office Equip.', 'N/A', 'N/A', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('WTR-FLT-002-2024', 'Water Filter', 'Office Equip.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.FUR-CH-067-2024', 'Office Organizer', 'Furn. & Fitt.', 'N/A', 'N/A', 1, 'Opns mger Office', 'HR dept', 'Good', 'Needs Repair', NULL, 1),
('CAL.FUR-CH-068-2024', 'Office Organizer', 'Furn. & Fitt.', 'N/A', 'N/A', 1, 'D/Legal affairs Off.', 'HR dept', 'Good', 'Needs Repair', NULL, 1),
('CAL.SCL-001-2024', 'Electronic Scale', 'Measuring equip', 'N/A', 'TCS-300KG', 1, 'Kagarama', 'Opns Dept', 'Brooken', 'Needs Repair', NULL, 1),
('CAL.SCL-001-2024', 'Electronic Scale', 'Measuring equip', 'N/A', 'TCS-300KG', 1, 'Bugesera', 'Opns Dept', 'Good', 'No issue', NULL, 1),
('CAL.FE-001-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'CAL Office (Kechten)', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-002-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'CAL Office (Arms storege)', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-003-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'Kagarama', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-004-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'Kagarama', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-005-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'Kagarama', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-006-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'Kagarama', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-007-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'Bugesera', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-008-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'Bugesera', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-009-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'Bugesera', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.FE-010-2024', 'Fire extinguisher', 'Fire and safety', 'N/A', '6kg powder', 1, 'Control room', 'HR dept', 'Needs service', 'expired powder', NULL, 1),
('CAL.SL-001-2024', 'Sport ligth', 'Eelectrical Eqpt.', 'N/A', 'LED', 1, 'Board room', 'HR dept', 'Good', 'check regularly', NULL, 1),
('CAL.SL-002-2024', 'Sport ligth', 'Eelectrical Eqpt.', 'N/A', 'LED', 1, 'Board room', 'HR dept', 'Good', 'check regularly', NULL, 1),
('CAL.SL-003-2024', 'Sport ligth', 'Eelectrical Eqpt.', 'N/A', 'LED', 1, 'Board room', 'HR dept', 'Good', 'check regularly', NULL, 1),
('CAL.SL-004-2024', 'Sport ligth', 'Eelectrical Eqpt.', 'N/A', 'LED', 1, 'Board room', 'HR dept', 'Good', 'check regularly', NULL, 1),
('CAL.SL-005-2024', 'Sport ligth', 'Eelectrical Eqpt.', 'N/A', 'LED', 1, 'Board room', 'HR dept', 'Good', 'check regularly', NULL, 1),
('CAL.SL-006-2024', 'Sport ligth', 'Eelectrical Eqpt.', 'N/A', 'LED', 1, 'Board room', 'HR dept', 'Good', 'check regularly', NULL, 1),
('CAL.SL-007-2024', 'Sport ligth', 'Eelectrical Eqpt.', 'N/A', 'LED', 1, 'Board room', 'HR dept', 'Good', 'check regularly', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL.SL-008-2024', 'Sport ligth', 'Eelectrical Eqpt.', 'N/A', 'LED', 1, 'Board room', 'HR dept', 'Good', 'check regularly', NULL, 1),
('CAL.OC-001-2024', 'Office cartens', 'Office Cartens', 'N/A', 'Vertcal blind cartens', 1, 'Co-CEO''s Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.OC-002-2024', 'Office cartens', 'Office Cartens', 'N/A', 'Vertcal blind cartens', 1, 'Board room', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-001-2024', 'Off. exective Desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Co-CEO', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-002-2024', 'Extension Desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Co-CEO', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-003-2023', 'Extension Desk', 'Office Furniture', 'N/A', 'MDF', 1, 'D/Legal affairs', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-004-2023', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Operation Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-005-2022', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Project Manager', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-006-2022', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Legal Advisor', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-007-2023', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Finance Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-008-2023', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Finance Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-009-2023', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Finance Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-010-2023', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'HR Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-011-2023', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'HR Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-012-2023', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'C/Room', 'HR dept', 'New', 'No issue', NULL, 1),
('CAL.FUR-013-2025', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Log & Proc office', 'HR dept', 'New', 'No issue', NULL, 1),
('CAL.FUR-014-2025', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Log & Proc office', 'HR dept', 'New', 'No issue', NULL, 1),
('CAL.FUR-015-2025', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'Log & Proc office', 'HR dept', 'New', 'No issue', NULL, 1),
('CAL.FUR-016-2025', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'IT Office', 'HR dept', 'New', 'No issue', NULL, 1),
('CAL.FUR-017-2025', 'Compture desk', 'Office Furniture', 'N/A', 'MDF', 1, 'IT Office', 'HR dept', 'New', 'No issue', NULL, 1),
('CAL.FUR-015-2024', 'Dinning table', 'Office Furniture', 'N/A', 'Wood & metalic foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-016-2024', 'Dinning table', 'Office Furniture', 'N/A', 'Wood & metalic foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-017-2024', 'Dinning table', 'Office Furniture', 'N/A', 'Wood & metalic foot', 1, 'CAL Office', 'HR dept', 'Good', 'No issue', NULL, 1),
('CAL.FUR-018-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-019-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-010-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-011-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-012-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-013-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-017-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-014-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-015-2024', 'Ordinary table Fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-016-2024', 'Dinning table fabric', 'Office Furniture', 'N/A', 'Wooden', 1, 'Bugesera', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-017-2024', 'Dinning table fabric', 'Office Furniture', 'N/A', 'Wood & Metalic', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-018-2024', 'Work station', 'Office Furniture', 'N/A', 'MDF with metalic foot', 1, 'Operation staff', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-019-2024', 'Confrence Room', 'Office Furniture', NULL, 'MDF with metalic foot', 1, 'Board Room', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-020-2023', 'Side table', 'Office Furniture', 'N/A', 'MDF', 1, 'D/Legal  Affairs', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-021-2024', 'Office Table', 'Office Furniture', 'N/A', 'MDF', 1, 'D/Legal  Affairs', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-022-2024', 'Office table', 'Office Furniture', 'N/A', 'MDF', 1, 'Operation Staff', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-001-2024', 'Closed cabinet half Glass1.80m', 'Office Furniture', 'N/A', 'MDF', 1, 'Co-CEO', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-002-2024', 'Closed cabinet half Glass1.80m', 'Office Furniture', 'N/A', 'Metali Filling cabinet', 1, 'D/ Legal affairs', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-003-2024', 'Safe cabinet', 'Office Furniture', 'N/A', 'Metal', 1, 'Co-CEO', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-004-2024', 'Small cabinet', 'Office Furniture', 'N/A', 'MDF', 1, 'Operation staff', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-005-2024', '4 drower Cabinet', 'Office Furniture', 'N/A', 'Metallic', 1, 'HR', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-006-2024', 'Small Cabinet', 'Office Furniture', 'N/A', 'Metallic', 1, 'HR', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.FUR-007-2024', 'Kitchen Cabinet', 'Office Furniture', 'N/A', 'WOOD', 1, 'Kitchen', 'HR dept.', 'Good', 'No issue', NULL, 1),
('CAL.WB-DD-001-2024', 'Wooden Bed DD', 'Acc. Furniture', 'N/A', 'Wood made', 53, 'Kagarama', 'Opns Dept.', 'Good', 'Needs P. check', NULL, 1),
('CAL.WB-S-001-2024', 'Metalic Bed DD', 'Acc. Furniture', 'N/A', 'Metalmade', 61, 'Kagarama', 'Opns Dept.', 'Good', 'Needs P. check', NULL, 1),
('CAL.MB-DD-001-2024', 'Wood Bed Single', 'Acc. Furniture', 'N/A', 'Woodl Made', 1, 'Kagarama', 'Opns Dept.', 'Good', 'Needs P. check', NULL, 1),
('CAL.MB-DD-001-2024', 'Wood bed Single', 'Acc. Furniture', 'N/A', 'Wooden', 6, 'Bugesera-Supervisor', 'Opns Dept.', 'Good', 'repair needed for broken', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL.MB-DD-001-2024', 'Metal bed Single', 'Acc. Furniture', 'N/A', 'Metal made', 2, 'Kabarore', 'Opns Dept.', 'Good', 'repair needed for broken', NULL, 1),
('CAL.MB-DD-001-2024', 'Metal bed Single', 'Acc. Furniture', 'N/A', 'Metal', 2, 'Kayonza', 'Opns Dept.', 'Good', 'repair needed for broken', NULL, 1),
('CAL.MB-DD-001-2024', 'Wood bed double', 'Acc. Furniture', 'N/A', 'Wooden', 1, 'Bugesra-Coord.', 'Opns Dept.', 'Good', 'repair needed for broken', NULL, 1),
('CAL.MB-DD-001-2024', 'Wooden Bed Double', 'Acc. Furniture', 'N/A', 'Wooden', 100, 'Bugesera-Nyab.', 'Opns Dept.', 'Good', 'repair needed for broken', NULL, 1),
('CAL.MB-DD-001-2024', 'Metallic Bed DD', 'Acc. Furniture', 'N/A', 'Metali bed', 0, 'Gashora', 'Opns Dept.', 'Good', 'repair needed for broken', NULL, 1),
('CAL.MB-DD-001-2024', 'Metallic Bed DD', 'Acc. Furniture', 'N/A', 'Metallic made', 15, 'Kinigi', 'Opns Dept.', 'Good', 'repair needed for broken', '2025-06-18', 1),
('CAL.MB-DD-001-2024', 'Metallic Bed DD', 'Acc. Furniture', 'N/A', 'Metallic made', 2, 'Musanze-karwaswa', 'Opns Dept.', 'Good', 'repair needed for broken', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 227, 'Kagarama', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 5, 'Huye', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 5, 'Ndua', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 216, 'Bugesra-nyab', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Matress Double', 1, 'Bugesera-coord', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 5, 'Juru', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 6, 'Gashora', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 4, 'kayonza', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 5, 'Kabarore', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2024', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 4, 'Musanze-karwaswa', 'Opns Dept.', 'Good', 'Periodic Inspection', NULL, 1),
('CAL.MS-S-001-2025', 'Matresses', 'Acc. Furniture', 'N/A', 'Sweet dream (dodoma)', 30, 'Kinigi', 'Opns Dept.', 'Good', 'Periodic Inspection', '2025-06-18', 1),
('CAL.DB-001-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Co-CEO Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-002-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Opns Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-003-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Log & proc Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-004-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Log & proc Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-005-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Opns & IT office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-006-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Opns & IT office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-007-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Opns & IT office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-008-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'HR Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-009-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'HR Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-010-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Log & proc Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-011-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Log & proc Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-012-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Log & proc Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-013-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-014-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.DB-015-2024', 'Dustbin', 'Cleaning. Eqpt', 'N/A', 'Plastic', 1, 'Bugesera', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.PM-001-2024', 'Punching Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.PM-002-2024', 'Punching Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Sales and mkt Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.PM-003-2024', 'Punching Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Operaton staff', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.PM-004-2024', 'Punching Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Finance', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.PM-005-2024', 'Punching Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Procurement', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.PM-006-2024', 'Punching Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Bugesera', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.PM-007-2024', 'Punching Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'CAL Store', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.PM-008-2024', 'Punching Machine', 'Off. Machines', 'N/A', 'PUNCHIN', 1, 'D/legal affairs', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-001-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Co-CEO''s Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-002-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Operation Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-003-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'sales amd maketing', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-004-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'Jijuang', 1, 'Operation Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-005-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'Kangaro', 1, 'Log & Procurement', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-006-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'JILIUNG', 1, 'HR', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-007-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'N/A', 1, 'Finance', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-008-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'N/A', 1, 'D/Legal affairs', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.SP-009-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'N/A', 1, 'Bugesera', 'HR dept', 'Good', 'No issues', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL.SP-010-2024', 'Spaplling Machine', 'Off. Machines', 'N/A', 'N/A', 1, 'reception', 'HR dept', NULL, 'No issues', NULL, 1),
('CAL-EA-001-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'Mercury', 1, 'Co-CEO office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-002-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'Mercury', 1, 'Operation Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-003-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'KadliS', 1, 'Project Manager', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-004-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'Mercury', 1, 'Hr Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-005-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'Mercury', 1, 'Board room', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-006-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'Mercury', 1, 'Finance', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-007-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'Mercury', 1, 'Finance', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-008-2025', 'Extention Cable', 'Off. accessories', 'N/A', 'KADLIS', 1, 'Procurement', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-009-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'EXTENSION', 1, 'Opns Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CA-LEA-010-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'MERCURY', 1, 'Log. & Procu', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-011-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'KADLIS', 1, 'Bugesera', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-012-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'KADLIS', 1, 'Bugesera', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-012-2025', 'Extention Cable', 'Off. accessories', 'N/A', 'KADLIS', 1, 'Bugesera', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-013-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'KADLIS', 1, 'Kagarama', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-014-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'MERCURY', 1, 'Sales and mkt', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-015-2024', 'Extention Cable', 'Off. accessories', 'N/A', 'MERCURY', 1, 'Legal Advisor', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-015-2025', 'Extention Cable', 'Off. accessories', 'N/A', 'KADLIS', 1, 'IT', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL-EA-015-2025', 'Extention Cable', 'Off. accessories', 'N/A', 'KADLIS', 1, 'Gender', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.001-OE-2024', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'Co-CEO', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.002-OE-2024', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'Operation Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.003-OE-2024', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'IT', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.004-OE-2024', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'Gender', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.005-OE-2024', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'Roster', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.006-OE-2025', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'Arms officer', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.007-OE-2025', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'Logistics', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.008-OE-2025', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'Reception', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.009-OE-2025', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'Kagarama', 'Opns Dept', 'Good', 'No issues', NULL, 1),
('CAL.010-OE-2025', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'CAL store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.011-OE-2025', 'Desk organiser', 'Office Eqpt.', 'N/A', 'wood', 1, 'CAL store', 'Log.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kitchen Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.002-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.003-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.004-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Musanze-Karwasa', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.005-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.006-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.007-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.008-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kayonza', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.010-KE-2025', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kinigi-Musanze', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.009-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kabarore', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.009-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Nduba', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.009-KE-2024', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Gashora', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.009-KE-2025', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Juru', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.011-KE-2026', 'Gaz cooker', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Huye', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kitchen Office', 'HR dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2025', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kitchen Office', 'HR dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kayonza', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kabarore', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kagarama', 'Opns Dept.', 'Good', 'No issues', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Bugesera', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Juru', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Gashora', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Nduba', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Musanze', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2025', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Kinigi', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2025', 'Gas Cylinder', 'Kitchen Eqpt.', 'N/A', 'N/A', 1, 'Huye', 'Opns Dept.', 'Good', 'No issues', NULL, 1),
('CAL. 001-KE-2024', 'Microwave', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kitchen Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL. 001-KE-2024', 'Aspirator', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kitchen Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL. 001-KE-2024', 'Think Cabinate', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kitchen Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL. 001-KE-2024', 'Coffee Maker', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kitchen Office', 'HR dept', 'Fair', 'repair needed for broken', NULL, 1),
('CAL. 001-KE-2024', 'Cutting Table', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kitchen Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL. 001-KE-2024', 'Electrical Flyer', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kitchen Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL. 001-KE-2024', 'Steel Shelve', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kitchen Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL. 001-KE-2024', 'Brender Machine', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kitchen Office', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Cooking Pan Big', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kagarama', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.002-KE-2024', 'Cooking Pan Big', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kagarama', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.003-KE-2024', 'Cooking Pan Big', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kagarama', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.004-KE-2024', 'Cooking Small Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kagarama', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.005-KE-2024', 'Cooking Small Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Kagarama', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.005-KE-2024', 'Cooking Small Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Bugesera', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.006-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Bugesera', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.007-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Bugesera', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.008-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Bugesera', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.009-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Bugesera', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.010-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Bugesera', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.011-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 1, 'Bugesera', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.005-KE-2024', 'Cooking Small Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 4, 'Kinigi', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.006-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 3, 'Karwasa', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.007-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 3, 'Nduba', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.008-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 3, 'Gashora', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.009-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 3, 'Juru', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.010-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 3, 'Kabarore', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.011-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 3, 'Kayonza', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.011-KE-2024', 'Cooking Big Pan', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 3, 'Huye', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Forks', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 215, 'Nyaba,Juru,Gashra,Kayoz& Gatsibo', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Plates', 'Kitchen Eqpt.', 'N/A', 'Milamine', 190, 'Nyaba,Juru,Gashra,Kayoz& Gatsibo', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Cups', 'Kitchen Eqpt.', 'N/A', 'Plastic', 115, 'Nyaba,Juru,Gashra,Kayoz& Gatsibo', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Forks', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 70, 'Kagarama,Nduba,& Huye', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Plates', 'Kitchen Eqpt.', 'N/A', 'Milamine', 210, 'Kagarama,Nduba,& Huye', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Cups', 'Kitchen Eqpt.', 'N/A', 'Plastic', 90, 'Kagarama,Nduba,& Huye', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Forks', 'Kitchen Eqpt.', 'N/A', 'Alumin st. steel', 35, 'Kinigi/ Karwasa', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Plates', 'Kitchen Eqpt.', 'N/A', 'Milamine', 35, 'Kinigi/ Karwasa', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL.001-KE-2024', 'Cups', 'Kitchen Eqpt.', 'N/A', 'Plastic', 35, 'Kinigi/ Karwasa', 'Opns.Dept', 'Good', 'No issues', NULL, 1),
('CAL. 006-MS-2024', 'Brand for centurion', 'Misc/Deco', 'N/A', 'WOODEN MDF', 1, 'Reception', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL. 007-MS-2024', 'Tente', 'Misc/Deco', 'N/A', 'TENT 20M*10M', 1, 'Bugesera', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.008-MS-2024', 'Partition', 'Misc/Deco', 'N/A', 'MAHOGANE', 1, 'Co-CEO', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.009-MS-2024', 'Kandagira', 'Misc/Deco', 'N/A', 'N/A', 1, 'Kagarama', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.010-MS-2024', 'Kandagira', 'Misc/Deco', 'N/A', 'N/A', 1, 'Kagarama', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.011-MS 2024', 'white board', 'Misc/Deco', 'N/A', 'N/A', 1, 'Meeting Room', 'HR dept', 'Good', 'No issues', NULL, 1);
INSERT INTO products ("assetId", name, category, "serialNumber", model, quantity, location, custodian, condition, notes, "purchaseDate", "lowStockThreshold") VALUES
('CAL.012-MS -2024', 'white board', 'Misc/Deco', 'N/A', 'N/A', 1, 'Project Mgr', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.013-MS-2024', 'Pen Holder', 'Misc/Deco', 'N/A', 'MDF', 1, 'D/legal  affairs', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.014-MS-2024', 'Pen Holder', 'Misc/Deco', 'N/A', 'MDF', 1, 'D/legal  affairs', 'HR dept', 'Good', 'No issues', NULL, 1),
('CAL.001-MV-2024', 'Motorcyle(RH970N)', 'Vehicle', 'LGTPCKYEOLH800101', 'Chain EMB2000', 1, 'Kagarama', 'Log. Dept.', 'Good', 'No issues', NULL, 1),
('CAL.002-MV-2024', 'Motorcyle(RH970N)', 'Vehicle', 'LGTPCKYEOLH800029', 'Chain EMB2001', 1, 'Kagarama', 'Log. Dept.', 'Good', 'No issues', NULL, 1);
COMMIT;
-- 555 items in batches of 50
